export type Status = 'Menunggu'|'Diproses'|'Selesai'|'Dibatalkan';
export type RequestItem={id:string;title:string;owner:string;category:string;status:Status;priority:string;quantity:number;budget:number;notes:string;createdAt:string;updatedAt:string};
export type EventItem={id:string;title:string;request:string;at:string};
export type QueueData={requests:RequestItem[];events:EventItem[]};
export const categories=['Operasional','Elektronik','Perlengkapan','Lainnya'];
export const statuses:Status[]=['Menunggu','Diproses','Selesai','Dibatalkan'];
export const KEY='queueiq-demo-v1';
export function seed():QueueData{const names=[['Restock kebutuhan pantry','Nadia Putri','Operasional'],['Logitech MX Master 3S','Andi Pratama','Elektronik'],['Perlengkapan onboarding','Sarah Wijaya','Perlengkapan'],['Kopi & susu mingguan','Bima Saputra','Operasional'],['Monitor Dell 27 inci','Rizky Maulana','Elektronik'],['Kertas A4 dan alat tulis','Dewi Lestari','Perlengkapan'],['Keyboard mechanical','Fajar Ramadhan','Elektronik'],['Snack untuk meeting','Nadia Putri','Operasional'],['Headset tim support','Andi Pratama','Elektronik'],['Kursi kerja ergonomis','Sarah Wijaya','Perlengkapan'],['Air mineral kantor','Bima Saputra','Operasional'],['Kabel USB-C','Rizky Maulana','Elektronik']];const states:Status[]=['Menunggu','Diproses','Menunggu','Selesai','Diproses','Menunggu','Selesai','Menunggu','Diproses','Menunggu','Selesai','Selesai'];const requests=names.map((n,i)=>({id:`QI-${1048-i}`,title:n[0],owner:n[1],category:n[2],status:states[i],priority:i===0||i===4?'Tinggi':'Normal',quantity:i%3+1,budget:[450000,1250000,850000,320000,3200000][i%5],notes:'Mohon disesuaikan dengan kebutuhan tim. Hubungi pemohon jika ada perubahan ketersediaan.',createdAt:new Date(Date.now()-(i+1)*720000).toISOString(),updatedAt:new Date(Date.now()-(i+1)*720000).toISOString()}));return {requests,events:requests.slice(0,3).map(r=>({id:r.id,title:r.status==='Diproses'?'Request mulai diproses':'Request ditambahkan',request:r.title,at:r.createdAt}))}}
export function validateDraft(d:any){if(!d||typeof d.title!=='string'||!d.title.trim()||d.title.trim().length>100)throw Error('Nama request wajib diisi, maksimal 100 karakter.');if(typeof d.owner!=='string'||!d.owner.trim()||d.owner.trim().length>60)throw Error('Nama pemohon wajib diisi, maksimal 60 karakter.');if(!categories.includes(d.category)||!['Normal','Tinggi'].includes(d.priority))throw Error('Kategori atau prioritas tidak valid.');if(!Number.isInteger(d.quantity)||d.quantity<1||d.quantity>999)throw Error('Jumlah harus 1 sampai 999.');if(!Number.isFinite(d.budget)||d.budget<0||d.budget>1000000000)throw Error('Anggaran tidak valid.');if(typeof d.notes!=='string'||d.notes.length>1000)throw Error('Catatan maksimal 1.000 karakter.');return {...d,title:d.title.trim(),owner:d.owner.trim()}}
export function createRequest(data:QueueData,draft:any):QueueData{const d=validateDraft(draft);const now=new Date().toISOString();const id=`QI-${Math.max(1048,...data.requests.map(r=>Number(r.id.slice(3))||0))+1}`;const request:RequestItem={...d,id,status:'Menunggu',createdAt:now,updatedAt:now};return {requests:[request,...data.requests],events:[{id:crypto.randomUUID(),title:'Request ditambahkan',request:d.title,at:now},...data.events].slice(0,50)}}
export function transition(data:QueueData,id:string,status:Status):QueueData{const r=data.requests.find(r=>r.id===id);if(!r)throw Error('Request tidak ditemukan.');const allowed:Record<Status,Status[]>={Menunggu:['Diproses','Dibatalkan'],Diproses:['Selesai','Dibatalkan'],Selesai:[],Dibatalkan:[]};if(!allowed[r.status].includes(status))throw Error('Perubahan status tidak diizinkan.');const now=new Date().toISOString();return {requests:data.requests.map(x=>x.id===id?{...x,status,updatedAt:now}:x),events:[{id:crypto.randomUUID(),title:`Request ${status.toLowerCase()}`,request:r.title,at:now},...data.events].slice(0,50)}}
export function parseData(raw:string):QueueData{const d=JSON.parse(raw);if(!Array.isArray(d.requests)||!Array.isArray(d.events))throw Error('Format data tidak valid.');d.requests.forEach((r:any)=>{validateDraft(r);if(typeof r.id!=='string'||!/^QI-\d+$/.test(r.id)||!statuses.includes(r.status)||!Number.isFinite(Date.parse(r.createdAt))||!Number.isFinite(Date.parse(r.updatedAt)))throw Error('Data request tidak valid.')});if(new Set(d.requests.map((r:any)=>r.id)).size!==d.requests.length)throw Error('ID duplikat.');d.events.forEach((e:any)=>{if(typeof e.id!=='string'||typeof e.title!=='string'||typeof e.request!=='string'||!Number.isFinite(Date.parse(e.at)))throw Error('Aktivitas tidak valid.')});return d}
export function nextRequest(data:QueueData){return data.requests.filter(r=>r.status==='Menunggu').sort((a,b)=>(Number(b.priority==='Tinggi')-Number(a.priority==='Tinggi'))||a.createdAt.localeCompare(b.createdAt))[0]}
